# Generated by Django 5.1.7 on 2025-03-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tugas',
            name='kategori',
            field=models.CharField(choices=[('kerja', 'Kerja'), ('pribadi', 'Pribadi'), ('belajar', 'Belajar')], default='kerja', max_length=20),
        ),
        migrations.AddField(
            model_name='tugas',
            name='status',
            field=models.CharField(choices=[('belum', 'Belum Selesai'), ('proses', 'Dalam Proses'), ('selesai', 'Selesai')], default='belum', max_length=20),
        ),
    ]
