# Generated by Django 5.1.7 on 2025-03-18 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0002_tugas_kategori_tugas_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tugas',
            options={'ordering': ['deadline', 'created_at']},
        ),
        migrations.AlterField(
            model_name='tugas',
            name='kategori',
            field=models.CharField(choices=[('kerja', 'Kerja'), ('pribadi', 'Pribadi'), ('perkuliahan', 'Perkuliahan')], default='kerja', max_length=20),
        ),
        migrations.AlterField(
            model_name='tugas',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
