# Generated by Django 5.1.7 on 2025-03-19 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0004_alter_tugas_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tugas',
            name='selesai',
        ),
    ]
