# Generated by Django 5.1.7 on 2025-03-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0005_remove_tugas_selesai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tugas',
            name='status',
            field=models.CharField(choices=[('belum', 'Belum Selesai'), ('selesai', 'Selesai')], default='belum', max_length=20),
        ),
    ]
