# Generated by Django 5.1.7 on 2025-03-26 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0006_alter_tugas_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tugas',
            options={'ordering': ['deadline', 'created_at'], 'verbose_name': 'Tugas', 'verbose_name_plural': 'Daftar Tugas'},
        ),
        migrations.AlterField(
            model_name='tugas',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada'),
        ),
        migrations.AlterField(
            model_name='tugas',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Pilih batas waktu penyelesaian tugas.', null=True, verbose_name='Batas Waktu'),
        ),
        migrations.AlterField(
            model_name='tugas',
            name='deskripsi',
            field=models.TextField(blank=True, help_text='Opsional: Deskripsikan tugas secara detail.', null=True, verbose_name='Deskripsi Tugas'),
        ),
        migrations.AlterField(
            model_name='tugas',
            name='judul',
            field=models.CharField(help_text='Masukkan judul tugas.', max_length=255, verbose_name='Judul Tugas'),
        ),
        migrations.AlterField(
            model_name='tugas',
            name='kategori',
            field=models.CharField(choices=[('kerja', 'Kerja'), ('pribadi', 'Pribadi'), ('perkuliahan', 'Perkuliahan')], db_index=True, default='kerja', help_text='Pilih kategori tugas.', max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='tugas',
            name='prioritas',
            field=models.CharField(choices=[('tinggi', 'Tinggi'), ('sedang', 'Sedang'), ('rendah', 'Rendah')], db_index=True, default='sedang', help_text='Tentukan prioritas tugas.', max_length=10, verbose_name='Prioritas'),
        ),
        migrations.AlterField(
            model_name='tugas',
            name='status',
            field=models.CharField(choices=[('belum', 'Belum Selesai'), ('selesai', 'Selesai')], db_index=True, default='belum', help_text='Tentukan status tugas (Belum Selesai atau Selesai).', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='tugas',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada'),
        ),
        migrations.AlterField(
            model_name='tugas',
            name='user',
            field=models.ForeignKey(help_text='Pilih pengguna yang memiliki tugas ini.', on_delete=django.db.models.deletion.CASCADE, related_name='tugas_user', to=settings.AUTH_USER_MODEL, verbose_name='Pemilik Tugas'),
        ),
    ]
