# Generated by Django 5.2.7 on 2026-02-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0007_alter_tugas_options_alter_tugas_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tugas',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done')], db_index=True, default='todo', help_text='Tentukan status tugas (To Do, In Progress, atau Done).', max_length=20, verbose_name='Status'),
        ),
    ]
