# Generated by Django 5.2.7 on 2026-02-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0008_alter_tugas_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tugas',
            name='status',
            field=models.CharField(choices=[('belum', 'Belum Selesai'), ('selesai', 'Selesai')], db_index=True, default='belum', help_text='Tentukan status tugas (Belum Selesai atau Selesai).', max_length=20, verbose_name='Status'),
        ),
    ]
