# Generated by Django 5.2.7 on 2026-02-26 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0009_alter_tugas_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(help_text='Masukkan judul subtask.', max_length=255, verbose_name='Judul Subtask')),
                ('selesai', models.BooleanField(default=False, help_text='Centang jika subtask sudah selesai.', verbose_name='Selesai')),
                ('urutan', models.IntegerField(default=0, help_text='Urutan tampilan subtask (semakin kecil semakin atas).', verbose_name='Urutan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('tugas', models.ForeignKey(help_text='Tugas utama yang memiliki subtask ini.', on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tugas.tugas', verbose_name='Tugas Utama')),
            ],
            options={
                'verbose_name': 'Subtask',
                'verbose_name_plural': 'Subtasks',
                'ordering': ['urutan', 'created_at'],
            },
        ),
    ]
