# Generated by Django 5.2.7 on 2026-02-26 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0010_subtask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('deadline_soon', 'Deadline Mendekati'), ('overdue', 'Melewati Deadline'), ('subtask_complete', 'Semua Subtask Selesai')], help_text='Jenis notifikasi.', max_length=20, verbose_name='Tipe Notifikasi')),
                ('pesan', models.CharField(help_text='Isi pesan notifikasi.', max_length=255, verbose_name='Pesan')),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='Status apakah notifikasi sudah dibaca.', verbose_name='Sudah Dibaca')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Dibuat Pada')),
                ('tugas', models.ForeignKey(blank=True, help_text='Tugas yang terkait dengan notifikasi ini.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tugas.tugas', verbose_name='Tugas Terkait')),
                ('user', models.ForeignKey(help_text='User yang menerima notifikasi.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Penerima')),
            ],
            options={
                'verbose_name': 'Notifikasi',
                'verbose_name_plural': 'Notifikasi',
                'ordering': ['-created_at'],
            },
        ),
    ]
