# Generated by Django 5.2.7 on 2026-07-27 01:00

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0011_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='judul',
            field=models.CharField(help_text='Masukkan judul subtask.', max_length=500, verbose_name='Judul Subtask'),
        ),
        migrations.CreateModel(
            name='AktivitasHarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(help_text='Masukkan judul aktivitas.', max_length=255, verbose_name='Judul Aktivitas')),
                ('jam_mulai', models.TimeField(help_text='Waktu mulai aktivitas.', verbose_name='Jam Mulai')),
                ('durasi_menit', models.PositiveIntegerField(help_text='Durasi aktivitas dalam menit.', verbose_name='Durasi (Menit)')),
                ('jam_selesai', models.TimeField(blank=True, help_text='Otomatis dihitung dari jam_mulai + durasi_menit.', null=True, verbose_name='Jam Selesai')),
                ('status', models.CharField(choices=[('belum', 'Belum'), ('selesai', 'Selesai'), ('terlewat', 'Terlewat')], db_index=True, default='belum', help_text='Status penyelesaian aktivitas.', max_length=10, verbose_name='Status')),
                ('is_habit', models.BooleanField(default=False, help_text='Jika dicentang, aktivitas ini akan otomatis diulang setiap hari.', verbose_name='Ulangi Setiap Hari')),
                ('tanggal', models.DateField(db_index=True, default=datetime.date.today, help_text='Tanggal aktivitas.', verbose_name='Tanggal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('user', models.ForeignKey(help_text='User yang memiliki aktivitas ini.', on_delete=django.db.models.deletion.CASCADE, related_name='aktivitas_harian', to=settings.AUTH_USER_MODEL, verbose_name='Pemilik')),
            ],
            options={
                'verbose_name': 'Aktivitas Harian',
                'verbose_name_plural': 'Aktivitas Harian',
                'ordering': ['tanggal', 'jam_mulai'],
            },
        ),
        migrations.CreateModel(
            name='EvaluasiMingguan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minggu_mulai', models.DateField(help_text='Tanggal awal periode minggu evaluasi.', verbose_name='Awal Minggu')),
                ('minggu_selesai', models.DateField(help_text='Tanggal akhir periode minggu evaluasi.', verbose_name='Akhir Minggu')),
                ('total_tugas', models.IntegerField(default=0, help_text='Jumlah tugas pada minggu tersebut.', verbose_name='Total Tugas')),
                ('tugas_selesai', models.IntegerField(default=0, help_text='Jumlah tugas yang diselesaikan.', verbose_name='Tugas Selesai')),
                ('persen_tugas', models.FloatField(default=0.0, help_text='Persentase penyelesaian tugas utama.', verbose_name='% Penyelesaian Tugas')),
                ('total_aktivitas', models.IntegerField(default=0, help_text='Jumlah aktivitas harian pada minggu tersebut.', verbose_name='Total Aktivitas')),
                ('aktivitas_selesai', models.IntegerField(default=0, help_text='Jumlah aktivitas harian yang diselesaikan.', verbose_name='Aktivitas Selesai')),
                ('persen_aktivitas', models.FloatField(default=0.0, help_text='Persentase penyelesaian aktivitas harian.', verbose_name='% Penyelesaian Aktivitas')),
                ('catatan_evaluasi', models.TextField(blank=True, default='', help_text='Catatan refleksi atau evaluasi mingguan dari user.', verbose_name='Catatan Evaluasi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('user', models.ForeignKey(help_text='User yang memiliki evaluasi ini.', on_delete=django.db.models.deletion.CASCADE, related_name='evaluasi_mingguan', to=settings.AUTH_USER_MODEL, verbose_name='Pemilik')),
            ],
            options={
                'verbose_name': 'Evaluasi Mingguan',
                'verbose_name_plural': 'Evaluasi Mingguan',
                'ordering': ['-minggu_mulai'],
                'unique_together': {('user', 'minggu_mulai')},
            },
        ),
    ]
