# Generated by Django 5.2.7 on 2026-07-29 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0012_alter_subtask_judul_aktivitasharian_evaluasimingguan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255, verbose_name='Judul Kegiatan')),
                ('kategori', models.CharField(choices=[('akademik', 'Akademik/Dosen'), ('pekerjaan', 'Pekerjaan'), ('sosial', 'Teman/Sosial'), ('acara', 'Acara/Event'), ('lainnya', 'Lainnya')], db_index=True, default='lainnya', max_length=20, verbose_name='Kategori')),
                ('tanggal', models.DateField(db_index=True, verbose_name='Tanggal')),
                ('jam_mulai', models.TimeField(verbose_name='Jam Mulai')),
                ('jam_selesai', models.TimeField(verbose_name='Jam Selesai')),
                ('lokasi', models.CharField(blank=True, default='', max_length=255, verbose_name='Lokasi / Link')),
                ('catatan', models.TextField(blank=True, default='', verbose_name='Catatan')),
                ('status', models.CharField(choices=[('akan_datang', 'Akan Datang'), ('selesai', 'Selesai'), ('dibatalkan', 'Dibatalkan')], db_index=True, default='akan_datang', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui Pada')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kegiatan', to=settings.AUTH_USER_MODEL, verbose_name='Pemilik')),
            ],
            options={
                'verbose_name': 'Kegiatan & Acara',
                'verbose_name_plural': 'Kegiatan & Acara',
                'ordering': ['tanggal', 'jam_mulai'],
            },
        ),
    ]
