# Generated by Django 5.2.7 on 2026-07-29 04:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0013_kegiatan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='aktivitasharian',
            index=models.Index(fields=['user', 'tanggal'], name='tugas_aktiv_user_id_139748_idx'),
        ),
        migrations.AddIndex(
            model_name='kegiatan',
            index=models.Index(fields=['user', 'tanggal'], name='tugas_kegia_user_id_6abe05_idx'),
        ),
    ]
