# Generated by Django 5.2.7 on 2026-07-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugas', '0014_aktivitasharian_tugas_aktiv_user_id_139748_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kegiatan',
            name='kategori',
            field=models.CharField(choices=[('akademik', 'Akademik'), ('pekerjaan', 'Pekerjaan'), ('keluarga', 'Keluarga'), ('pribadi_sosial', 'Pribadi & Sosial'), ('acara', 'Acara/Event'), ('lainnya', 'Lainnya')], db_index=True, default='lainnya', max_length=20, verbose_name='Kategori'),
        ),
    ]
